<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-02 23:44:30</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>crafting_process.py:1767</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception resuming Element (AttributeError: type object 'ComponentContainer' has no attribute 'on_crafting_process_finished')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4049, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1134, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5453, in _exit&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5443, in _exit&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_process.py", line 1767, in auto_increment_phase&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 468, in exported_funcAttributeError: type object 'ComponentContainer' has no attribute 'on_crafting_process_finished'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 01:22:05</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>client.py:511</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[sscholl] Exception processing ResetRecord:&lt;collectibles_Lightsaber_Hilt_Protection_1:0x02a9121762088fef, reason:ResetReason.BEING_DESTROYED, stage:_Stage.INTERNAL_STATE_RESET, being_processed:True, source:None, cause:None. This will result in a partially reset object (AttributeError: 'NoneType' object has no attribute 'cancel_live_dragging')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 219, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\persistence_service.py", line 451, in call_save_game_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 462, in request_client_disconnect_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 859, in on_teardown&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 332, in trigger_batch_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 325, in trigger_batch_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 426, in start_processing&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 450, in _process&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 601, in _process_one_record&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\client_object_mixin.py", line 819, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 931, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_object.py", line 389, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\live_drag_component.py", line 111, in component_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 757, in cancel_live_drag&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 511, in cancel_live_drag_on_objects&#13;&#10;AttributeError: 'NoneType' object has no attribute 'cancel_live_dragging'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 02:14:17</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>proxy.py:124</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 4577, in set_beginning_target_refs_states&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 470, in exported_func&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 3070, in set_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 3133, in _trigger_on_state_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 355, in on_state_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 02:14:31</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:1249</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception when applying action &lt;AwardWhimBucksLootOp ParticipantType.Actor&gt; for loot &lt;class 'sims4.tuning.instances.loot_WhimBucks_50'&gt; (AttributeError: 'NoneType' object has no attribute 'apply_satisfaction_points_delta')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\outcome.py", line 166, in on_loot&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 157, in apply_operations&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 597, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot_basic_op.py", line 303, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot_ops.py", line 741, in _apply_to_subject_and_target&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 1249, in apply_satisfaction_points_delta&#13;&#10;AttributeError: 'NoneType' object has no attribute 'apply_satisfaction_points_delta'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 02:14:31</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>loot_ops.py:741</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: 'NoneType' object has no attribute 'apply_satisfaction_points_delta')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\outcome.py", line 166, in on_loot&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 157, in apply_operations&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 598, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 595, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot_basic_op.py", line 303, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot_ops.py", line 741, in _apply_to_subject_and_target&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 1249, in apply_satisfaction_points_deltaAttributeError: 'NoneType' object has no attribute 'apply_satisfaction_points_delta'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 02:14:46</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[sscholl] Exception processing ResetRecord:&lt;droid_R_Series:0x02a91217901cde7d, reason:ResetReason.BEING_DESTROYED, stage:_Stage.INTERNAL_STATE_RESET, being_processed:True, source:None, cause:None. This will result in a partially reset object (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 219, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\persistence_service.py", line 451, in call_save_game_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 462, in request_client_disconnect_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 859, in on_teardown&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 332, in trigger_batch_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 325, in trigger_batch_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 426, in start_processing&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 450, in _process&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 601, in _process_one_record&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\client_object_mixin.py", line 819, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 931, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_object.py", line 389, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 381, in component_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 412, in _set_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 02:14:47</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception thrown while calling remove on droid_R_Series:0x02a91217901cde7d (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 219, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\persistence_service.py", line 451, in call_save_game_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 462, in request_client_disconnect_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 859, in on_teardown&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 332, in trigger_batch_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 325, in trigger_batch_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 426, in start_processing&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 450, in _process&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 566, in _process_one_record&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_object.py", line 395, in on_reset_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 724, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 161, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 289, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 343, in call_on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\game_object.py", line 1000, in on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 175, in on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:03:59</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:04:07</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>proxy.py:124</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 4937, in _timed_trigger_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 4972, in _set_state_value&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 3070, in set_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 3133, in _trigger_on_state_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 355, in on_state_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:05:31</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[sscholl] Exception processing ResetRecord:&lt;droid_R_Series:0x02a912179c86fef7, reason:ResetReason.BEING_DESTROYED, stage:_Stage.INTERNAL_STATE_RESET, being_processed:True, source:None, cause:None. This will result in a partially reset object (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 219, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\persistence_service.py", line 451, in call_save_game_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 462, in request_client_disconnect_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 859, in on_teardown&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 332, in trigger_batch_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 325, in trigger_batch_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 426, in start_processing&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 450, in _process&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 601, in _process_one_record&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\client_object_mixin.py", line 819, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 931, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_object.py", line 389, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 381, in component_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 412, in _set_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:05:31</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception thrown while calling remove on droid_R_Series:0x02a912179c86fef7 (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 219, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\persistence_service.py", line 451, in call_save_game_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 462, in request_client_disconnect_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 859, in on_teardown&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 332, in trigger_batch_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 325, in trigger_batch_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 426, in start_processing&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 450, in _process&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 566, in _process_one_record&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_object.py", line 395, in on_reset_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 724, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 161, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 289, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 343, in call_on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\game_object.py", line 1000, in on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 175, in on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:14:26</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>proxy.py:124</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 4937, in _timed_trigger_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 4972, in _set_state_value&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 3070, in set_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 3133, in _trigger_on_state_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 355, in on_state_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:14:36</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:15:30</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:15:33</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:470</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception resuming Element (AttributeError: 'NoneType' object has no attribute 'finished')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\routing.py", line 611, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 470, in exported_func&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\routing_component.py", line 1086, in set_routing_pathAttributeError: 'NoneType' object has no attribute 'finished'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:15:44</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:15:47</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:15:49</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:16:43</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:470</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception resuming Element (AttributeError: 'NoneType' object has no attribute 'finished')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\routing.py", line 611, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 470, in exported_func&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\routing_component.py", line 1086, in set_routing_pathAttributeError: 'NoneType' object has no attribute 'finished'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:17:01</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:17:02</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:17:21</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:17:46</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[sscholl] Exception processing ResetRecord:&lt;droid_R_Series:0x02a912179ead0344, reason:ResetReason.BEING_DESTROYED, stage:_Stage.INTERNAL_STATE_RESET, being_processed:True, source:None, cause:None. This will result in a partially reset object (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 219, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\persistence_service.py", line 451, in call_save_game_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 462, in request_client_disconnect_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 859, in on_teardown&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 332, in trigger_batch_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 325, in trigger_batch_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 426, in start_processing&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 450, in _process&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 601, in _process_one_record&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\client_object_mixin.py", line 819, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 931, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_object.py", line 389, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 381, in component_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 412, in _set_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:17:46</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception thrown while calling remove on droid_R_Series:0x02a912179ead0344 (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 219, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\persistence_service.py", line 451, in call_save_game_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 462, in request_client_disconnect_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 859, in on_teardown&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 332, in trigger_batch_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 325, in trigger_batch_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 426, in start_processing&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 450, in _process&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 566, in _process_one_record&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_object.py", line 395, in on_reset_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 724, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 161, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 289, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 343, in call_on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\game_object.py", line 1000, in on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 175, in on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:48:52</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:49:01</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>proxy.py:124</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 4937, in _timed_trigger_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 4972, in _set_state_value&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 3070, in set_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 3133, in _trigger_on_state_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 355, in on_state_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:49:17</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:49:21</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:49:50</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>proxy.py:124</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_elements.py", line 176, in _behavior_element&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\interaction_elements.py", line 448, in _do_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 470, in exported_func&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 3070, in set_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 3133, in _trigger_on_state_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 355, in on_state_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:53:30</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>proxy.py:124</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 4577, in set_beginning_target_refs_states&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 470, in exported_func&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 3070, in set_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 3133, in _trigger_on_state_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 355, in on_state_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:53:48</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[sscholl] Exception processing ResetRecord:&lt;droid_R_Series:0x02a91217a71c141c, reason:ResetReason.BEING_DESTROYED, stage:_Stage.INTERNAL_STATE_RESET, being_processed:True, source:None, cause:None. This will result in a partially reset object (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 219, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\persistence_service.py", line 451, in call_save_game_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 462, in request_client_disconnect_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 859, in on_teardown&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 332, in trigger_batch_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 325, in trigger_batch_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 426, in start_processing&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 450, in _process&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 601, in _process_one_record&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\client_object_mixin.py", line 819, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 931, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_object.py", line 389, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 381, in component_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 412, in _set_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 03:53:48</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception thrown while calling remove on droid_R_Series:0x02a91217a71c141c (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 219, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\persistence_service.py", line 451, in call_save_game_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 462, in request_client_disconnect_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 859, in on_teardown&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 332, in trigger_batch_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 325, in trigger_batch_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 426, in start_processing&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 450, in _process&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 566, in _process_one_record&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_object.py", line 395, in on_reset_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 459, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 161, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 289, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 343, in call_on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\game_object.py", line 1000, in on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 175, in on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 04:50:15</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 04:51:14</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>proxy.py:124</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception in Sim Timeline: Exception running Element (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 4937, in _timed_trigger_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 4972, in _set_state_value&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 3070, in set_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\state.py", line 3133, in _trigger_on_state_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 355, in on_state_changed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 04:51:51</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 04:52:00</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 04:52:05</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 04:52:07</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[tastle] Exception thrown while processing navmesh update callbacks. Eating this exception to prevent the alarm from self-destructing. (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 121, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 293, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1530, in _check_navmesh_updated_alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 1479, in _update_navmesh_id_if_neccessary&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 224, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 322, in _on_navmesh_updated&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 482, in restart_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 508, in stop_running_object_routing_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 04:52:16</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>[sscholl] Exception processing ResetRecord:&lt;droid_R_Series:0x02a91217b538376e, reason:ResetReason.BEING_DESTROYED, stage:_Stage.INTERNAL_STATE_RESET, being_processed:True, source:None, cause:None. This will result in a partially reset object (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 219, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\persistence_service.py", line 451, in call_save_game_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 462, in request_client_disconnect_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 859, in on_teardown&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 332, in trigger_batch_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 325, in trigger_batch_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 426, in start_processing&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 450, in _process&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 601, in _process_one_record&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\client_object_mixin.py", line 819, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 931, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_object.py", line 389, in on_reset_internal_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 381, in component_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 412, in _set_running_behavior&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>eaf4ede4ce3821e659478cb</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-03 04:52:17</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>__init__.py:202</categoryid><desyncid>eaf4ede4ce3821e659478cb</desyncid><systemconfig/><screenshot/><desyncdata>Exception thrown while calling remove on droid_R_Series:0x02a91217b538376e (AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 219, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\persistence_service.py", line 451, in call_save_game_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 462, in request_client_disconnect_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 859, in on_teardown&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 332, in trigger_batch_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 325, in trigger_batch_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 426, in start_processing&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 450, in _process&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 566, in _process_one_record&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_object.py", line 395, in on_reset_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 724, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 161, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 289, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 343, in call_on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\game_object.py", line 1000, in on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 98, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 175, in on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\routing\object_routing\object_routing_component.py", line 251, in _remove_target_callbacks&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\proxy.py", line 124, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;AttributeError: 'object_terrain' object has no attribute 'is_on_location_changed_callback_registered'rtim=0&#13;&#10;Client Session Time: 21.35&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,86,0,5599&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1050 Ti nvldumdx.dll 31.0.15.3623, GUID: D7B71E3E-5FC2-11CF-CF79-6B170EC2D235&#13; &#10;</desyncdata></report>
</root>